# Generated by Django 4.0.6 on 2022-07-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='access_type',
            field=models.BooleanField(default=False),
        ),
    ]
