# Generated by Django 4.0.6 on 2022-07-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Library_system', '0004_book_status_alter_order_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
